
name: Pull request tracker
on:
  pull_request:
    types: [opened]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Pull_request details
      run: |
          echo "Pull request creator: ${{ github.event.pull_request.user.login }}"
          echo "Pull request title: ${{ github.event.pull_request.title }}"
          echo "Pull request number: ${{ github.event.pull_request.number }}"
          echo "Pull request url: ${{ github.event.pull_request.html_url }}"
          echo "Pull request reviewers: ${{ github.event.pull_request.requested_reviewers }}"
